name: Test
on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'Formula/*.rb'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  install-test:
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - macos: macOS-13
          xcode: "14.3"
        - macos: macOS-12
          xcode: "14.1"
        - macos: macOS-12
          xcode: "13.4.1"
        - macos: macOS-11
          xcode: "13.1"
        - macos: macOS-11
          xcode: "12.5"
    env:
      BUNDLE_JOBS: 4
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v4
      - run: brew update
      - name: Create new tap
        run: |
          brew tap-new --no-git manicmaniac/tap
          cp Formula/*.rb "$(brew --repository manicmaniac/tap)/Formula"
      - name: Audit formulas
        run: |
          for file in "$(brew --repository manicmaniac/tap)/Formula/"*
          do
            brew audit --formula "$(basename "$file" .rb)"
          done
      - run: brew install --formula Formula/*.rb
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          path: |
            ~/Library/Logs/Homebrew/xcnew/
            ~/Library/Logs/Homebrew/class-dump/
      - run: brew test Formula/*.rb
      - run: brew uninstall --formula Formula/*.rb
  status-check:
    runs-on: ubuntu-22.04
    needs: install-test
    if: failure()
    steps:
      - run: exit 1
