name: Test
on: [push]
jobs:
  install-test:
    runs-on: macOS-10.15
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.4", "12", "11.7", "11.2.1"]
    steps:
      - uses: actions/checkout@v2
      - run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - run: brew update
      - run: brew audit --formulae Formula/*.rb
      - run: brew install --formulae Formula/*.rb
      - run: brew test Formula/*.rb
      - run: brew uninstall --formulae Formula/*.rb
