name: Test
on:
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'Formula/*.rb'
jobs:
  install-test:
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.1", "13.4.1", "13.1", "12.5"]
        include:
        - macos: macOS-12
          xcode: "14.1"
        - macos: macOS-12
          xcode: "13.4.1"
        - macos: macOS-11
          xcode: "13.1"
        - macos: macOS-11
          xcode: "12.5"
    env:
      BUNDLE_JOBS: 4
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - run: brew update
      - run: brew audit --formulae Formula/*.rb
      - run: brew install --formulae Formula/*.rb
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          path: |
            ~/Library/Logs/Homebrew/xcnew/
            ~/Library/Logs/Homebrew/class-dump/
      - run: brew test Formula/*.rb
      - run: brew uninstall --formulae Formula/*.rb
