name: Test
on: [push]
jobs:
  install-test:
    runs-on: ${{ matrix.macos }}
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.1", "13.0", "12.5", "12.4", "12", "11.7", "11.2.1"]
        include:
        - macos: macOS-11
          xcode: "13.1"
        - macos: macOS-11
          xcode: "13.0"
        - macos: macOS-11
          xcode: "12.5"
        - macos: macOS-10.15
          xcode: "12.4"
        - macos: macOS-10.15
          xcode: "12"
        - macos: macOS-10.15
          xcode: "11.7"
        - macos: macOS-10.15
          xcode: "11.2.1"
    env:
      BUNDLE_JOBS: 4
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - run: brew update
      # Workaround for https://github.com/Homebrew/brew/issues/12506
      - run: brew tap-new --no-git manicmaniac/tap
      - run: cp Formula/xcnew.rb $(brew --repo manicmaniac/tap)/Formula
      - run: brew audit --formulae manicmaniac/tap/xcnew
      - run: brew install --formulae Formula/xcnew.rb
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: ~/Library/Logs/Homebrew/xcnew/
      - run: brew test Formula/*.rb
      - run: brew uninstall --formulae Formula/*.rb
