name: Test
on: [push]
jobs:
  install-test:
    runs-on: macOS-10.15
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.4", "12", "11.7", "11.2.1"]
    env:
      BUNDLE_JOBS: 4
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      HOMEBREW_ARCH: native
    steps:
      - uses: actions/checkout@v2
      - run: brew update
      - run: brew audit --formulae Formula/*.rb
      - run: brew install --formulae Formula/*.rb
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          path: ~/Library/Logs/Homebrew/xcnew/
      - run: brew test Formula/*.rb
      - run: brew uninstall --formulae Formula/*.rb
